/* Caderno Inteligente Work V3 FINAL — offline + update-safe service worker */
var CACHE='caderno-inteligente-work-v3-1-final-20260914';
var ASSETS=['./','./index.html','./manifest.webmanifest','./orbita-infinity.css','./orbita-infinity.js','./caderno-work.css','./caderno-work.js','./work-icons.svg','./icons/icon-180.png','./icons/icon-192.png','./icons/icon-512.png'];
self.addEventListener('install',function(e){e.waitUntil(caches.open(CACHE).then(function(c){return c.addAll(ASSETS)}).catch(function(){}).then(function(){return self.skipWaiting()}))});
self.addEventListener('activate',function(e){e.waitUntil(Promise.all([caches.keys().then(function(keys){return Promise.all(keys.map(function(k){return k===CACHE?null:caches.delete(k)}))}),self.registration.navigationPreload&&self.registration.navigationPreload.enable?self.registration.navigationPreload.enable():Promise.resolve()]).then(function(){return self.clients.claim()}))});
self.addEventListener('message',function(e){if(e.data==='SKIP_WAITING')self.skipWaiting()});
function netFirst(req,fallback){return fetch(req,{cache:'no-store'}).then(function(resp){if(resp&&resp.ok)caches.open(CACHE).then(function(c){c.put(req,resp.clone())});return resp}).catch(function(){return caches.match(req).then(function(hit){return hit||caches.match(fallback||'./index.html')})})}
function stale(req){return caches.match(req).then(function(hit){var net=fetch(req).then(function(resp){if(resp&&resp.ok)caches.open(CACHE).then(function(c){c.put(req,resp.clone())});return resp}).catch(function(){return hit});return hit||net})}
self.addEventListener('fetch',function(e){var req=e.request;if(req.method!=='GET')return;var u;try{u=new URL(req.url)}catch(_){return}if(u.origin!==self.location.origin)return;if(u.pathname.endsWith('/config.js')){e.respondWith(netFirst(req,'./config.js'));return}if(req.mode==='navigate'||u.pathname.endsWith('/index.html')||u.pathname.endsWith('/')){e.respondWith(netFirst(req,'./index.html'));return}e.respondWith(stale(req))});
