-- ÓRBITA INFINITY V26 · colaboração segura por sala
create extension if not exists pgcrypto;

create table if not exists public.orbita_shared_files (
  id uuid primary key default gen_random_uuid(),
  share_code text unique not null,
  owner_id uuid not null default auth.uid(),
  title text not null default 'Arquivo Vivo',
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.orbita_shared_members (
  room_id uuid not null references public.orbita_shared_files(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  role text not null default 'editor' check (role in ('viewer','editor')),
  joined_at timestamptz not null default now(),
  primary key(room_id,user_id)
);
create table if not exists public.orbita_shared_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.orbita_shared_files(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  kind text not null default 'comment',
  message text not null default '',
  created_at timestamptz not null default now()
);

alter table public.orbita_shared_files enable row level security;
alter table public.orbita_shared_members enable row level security;
alter table public.orbita_shared_events enable row level security;

drop policy if exists "orbita room insert" on public.orbita_shared_files;
create policy "orbita room insert" on public.orbita_shared_files for insert to authenticated with check(owner_id=auth.uid());
drop policy if exists "orbita room read" on public.orbita_shared_files;
create policy "orbita room read" on public.orbita_shared_files for select to authenticated using(owner_id=auth.uid() or exists(select 1 from public.orbita_shared_members m where m.room_id=id and m.user_id=auth.uid()));
drop policy if exists "orbita room update" on public.orbita_shared_files;
create policy "orbita room update" on public.orbita_shared_files for update to authenticated using(owner_id=auth.uid() or exists(select 1 from public.orbita_shared_members m where m.room_id=id and m.user_id=auth.uid() and m.role='editor')) with check(owner_id=owner_id);

drop policy if exists "orbita member self read" on public.orbita_shared_members;
create policy "orbita member self read" on public.orbita_shared_members for select to authenticated using(user_id=auth.uid());
drop policy if exists "orbita member self insert" on public.orbita_shared_members;
create policy "orbita member self insert" on public.orbita_shared_members for insert to authenticated with check(user_id=auth.uid());

drop policy if exists "orbita events read" on public.orbita_shared_events;
create policy "orbita events read" on public.orbita_shared_events for select to authenticated using(exists(select 1 from public.orbita_shared_files f where f.id=room_id and (f.owner_id=auth.uid() or exists(select 1 from public.orbita_shared_members m where m.room_id=f.id and m.user_id=auth.uid()))));
drop policy if exists "orbita events insert" on public.orbita_shared_events;
create policy "orbita events insert" on public.orbita_shared_events for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from public.orbita_shared_files f where f.id=room_id and (f.owner_id=auth.uid() or exists(select 1 from public.orbita_shared_members m where m.room_id=f.id and m.user_id=auth.uid()))));

create or replace function public.orbita_join_room(p_code text)
returns table(room_id uuid,title text,state jsonb,updated_at timestamptz,role text)
language plpgsql security definer set search_path=public as $$
declare rid uuid; begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select f.id into rid from public.orbita_shared_files f where upper(f.share_code)=upper(trim(p_code)) limit 1;
  if rid is null then return; end if;
  insert into public.orbita_shared_members(room_id,user_id,role) values(rid,auth.uid(),'editor') on conflict(room_id,user_id) do nothing;
  return query select f.id,f.title,f.state,f.updated_at,coalesce((select m.role from public.orbita_shared_members m where m.room_id=f.id and m.user_id=auth.uid()),'editor') from public.orbita_shared_files f where f.id=rid;
end $$;
revoke all on function public.orbita_join_room(text) from public;
grant execute on function public.orbita_join_room(text) to authenticated;
